kind: "BuildConfig"
apiVersion: "v1"
runPolicy: Serial
metadata:
  name: "bc-colbert"
  namespace: richardmproject
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/terrierteam/ColBERT"
  strategy:
    type: Docker
    dockerStrategy:
  output:
    to:
      kind: "ImageStreamTag"
      name: "is-colbert:latest"
